"""Writers for theme artifacts."""

from __future__ import annotations

from pathlib import Path


def write_theme(xml: str, out_path: Path) -> Path:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(xml, encoding="utf-8")
    return out_path


def write_preview_html(xml: str, out_path: Path, title: str = "BloggerEasy Preview") -> Path:
    """Emit responsive preview HTML sidecar alongside the XML for local browser check."""
    preview_path = out_path.with_suffix(".preview.html")

    # Extract body content from XML for preview
    css = _extract_css(xml)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: system-ui, sans-serif;
            margin: 0;
            padding: 1.5rem;
            background: #f8fafc;
            color: #222;
            line-height: 1.6;
        }}
        .container {{
            max-width: 960px;
            margin: 0 auto;
            background: #fff;
            border-radius: 12px;
            box-shadow: 0 2px 20px rgba(0,0,0,0.08);
            padding: 2rem;
        }}
        h1 {{
            margin-top: 0;
            font-size: 1.75rem;
            color: #1a73e8;
            border-bottom: 2px solid #e5e7eb;
            padding-bottom: 0.75rem;
        }}
        .meta {{
            font-size: 0.85rem;
            color: #64748b;
            margin-bottom: 2rem;
        }}
        {css}
    </style>
</head>
<body>
    <div class="container">
        <h1>📄 {title}</h1>
        <p class="meta">Generated by BloggerEasy · Responsive Preview</p>
        <div class="content">
            <p>✅ Blogger XML theme generated successfully.</p>
            <p>XML file: <code>{out_path.name}</code></p>
            <p>Lines: {xml.count(chr(10))}</p>
            <p>Size: {len(xml):,} bytes</p>
        </div>
        <hr style="margin: 2rem 0; border: none; border-top: 1px solid #e5e7eb;">
        <details>
            <summary style="cursor:pointer;font-weight:600;color:#1a73e8;">🔍 View XML source</summary>
            <pre style="background:#1e293b;color:#e2e8f0;padding:1rem;border-radius:8px;overflow-x:auto;font-size:0.8rem;max-height:60vh;"><code>{_escape_html(xml[:5000])}</code></pre>
        </details>
    </div>
</body>
</html>"""
    preview_path.write_text(html, encoding="utf-8")
    return preview_path


def _extract_css(xml: str) -> str:
    """Extract inline CSS from Blogger XML for preview."""
    css_parts = []
    for line in xml.split("\n"):
        stripped = line.strip()
        if stripped.startswith(".") or stripped.startswith("#") or stripped.startswith("@"):
            css_parts.append(stripped)
    if css_parts:
        return "\n".join(css_parts[-30:])  # Last 30 CSS rules
    return ""


def _escape_html(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
