"""RSS feed generator for BloggerEasy."""
import xml.etree.ElementTree as ET
from datetime import datetime

def generate_rss(posts, site_url, title="Blog", description="Generated by BloggerEasy", out_path="rss.xml"):
    rss = ET.Element("rss", version="2.0")
    channel = ET.SubElement(rss, "channel")
    ET.SubElement(channel, "title").text = title
    ET.SubElement(channel, "link").text = site_url
    ET.SubElement(channel, "description").text = description
    for post in posts:
        item = ET.SubElement(channel, "item")
        ET.SubElement(item, "title").text = post.get("title", "")
        ET.SubElement(item, "link").text = site_url + post.get("slug", "")
        ET.SubElement(item, "description").text = post.get("summary", "")
        ET.SubElement(item, "pubDate").text = post.get("date", datetime.now().isoformat())
    tree = ET.ElementTree(rss)
    tree.write(out_path, encoding="utf-8", xml_declaration=True)
    return out_path
