from __future__ import annotations

from html import escape
from pathlib import Path


def write_theme(xml: str, out_path: Path) -> Path:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(xml, encoding="utf-8")
    return out_path


def write_preview_html(xml: str, out_path: Path, *, title: str = "BloggerEasy Preview") -> Path:
    """Write a lightweight static HTML preview sidecar next to the theme XML."""
    preview_path = out_path.with_suffix(".html")
    preview_path.parent.mkdir(parents=True, exist_ok=True)
    safe_title = escape(title)
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>{safe_title} · BloggerEasy preview</title>
  <style>
    body {{ margin:0; font-family:system-ui,sans-serif; color:#222; background:#fff; }}
    header {{ background:#1a73e8; color:#fff; padding:1.5rem 2rem; }}
    header h1 {{ margin:0; font-family:Georgia,serif; }}
    nav {{ display:flex; gap:1rem; padding:0.75rem 2rem; background:#34a853; }}
    nav a {{ color:#fff; text-decoration:none; font-weight:600; }}
    .wrap {{ max-width:960px; margin:1.25rem auto; padding:0 1rem; }}
    main {{ background:rgba(0,0,0,0.03); border-radius:12px; padding:1.25rem; }}
    footer {{ text-align:center; padding:1rem; color:#666; font-size:0.85rem; }}
    .badge {{ display:inline-block; background:#34a853; color:#fff; padding:0.2rem 0.5rem; border-radius:6px; font-size:0.75rem; }}
  </style>
</head>
<body>
  <header>
    <span class="badge">preview</span>
    <h1>{safe_title}</h1>
    <p>Static preview generated by BloggerEasy</p>
  </header>
  <nav><a href="#">Home</a><a href="#">About</a></nav>
  <div class="wrap">
    <main>
      <h2>Theme Preview</h2>
      <p>Import the companion XML file into Blogger Theme &rarr; Backup/Restore to go live.</p>
    </main>
  </div>
  <footer>Static preview sidecar &middot; BloggerEasy</footer>
</body>
</html>
"""
    preview_path.write_text(html, encoding="utf-8")
    return preview_path
