"""Static HTML preview of theme structure (not full Blogger runtime)."""

from __future__ import annotations

from html import escape
from pathlib import Path


def structure_to_preview_html(structure: dict) -> str:
    """Render a lightweight static HTML mock from a theme structure dict."""
    title = escape(str(structure.get("title") or "My Blog"))
    colors = structure.get("colors") or {}
    primary = escape(str(colors.get("primary") or "#1a73e8"))
    secondary = escape(str(colors.get("secondary") or "#34a853"))
    background = escape(str(colors.get("background") or "#ffffff"))
    text = escape(str(colors.get("text") or "#222222"))
    fonts = structure.get("fonts") or {}
    body_font = escape(str(fonts.get("body") or "system-ui, sans-serif"))
    heading_font = escape(str(fonts.get("heading") or "Georgia, serif"))
    layout = str(structure.get("layout") or "single-column")
    sidebar = bool((structure.get("features") or {}).get("sidebar")) or layout == "two-column"
    nav = structure.get("nav_links") or []
    nav_html = "".join(f'<a href="#">{escape(str(n.get("label") or "Link"))}</a>' for n in nav[:8])
    if not nav_html:
        nav_html = '<a href="#">Home</a><a href="#">About</a>'
    desc = escape(str(structure.get("description") or "Preview generated by BloggerEasy"))
    paras = structure.get("sample_paragraphs") or [
        "This is a static preview of your Blogger theme structure.",
        "Import the companion XML into Blogger Theme -> Backup/Restore to go live.",
    ]
    body = "".join(f"<p>{escape(str(p))}</p>" for p in paras[:4])
    aside = ""
    if sidebar:
        aside = (
            f'<aside class="sidebar"><h3>Sidebar</h3>'
            f'<p style="color:{secondary}">Widgets &amp; labels appear here in Blogger.</p></aside>'
        )
    grid = "1fr 280px" if sidebar else "1fr"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>{title} . BloggerEasy preview</title>
  <style>
    body {{ margin:0; font-family:{body_font}; color:{text}; background:{background}; }}
    header {{ background:{primary}; color:#fff; padding:1.5rem 2rem; }}
    header h1 {{ font-family:{heading_font}; margin:0; }}
    nav {{ display:flex; gap:1rem; padding:0.75rem 2rem; background:{secondary}; }}
    nav a {{ color:#fff; text-decoration:none; font-weight:600; }}
    .wrap {{ display:grid; grid-template-columns:{grid}; gap:1.25rem; max-width:960px; margin:1.25rem auto; padding:0 1rem; }}
    main {{ min-height:18rem; }}
    .sidebar {{ background:#f8fafc; border:1px solid #e2e8f0; border-radius:8px; padding:1rem; }}
    .sidebar h3 {{ margin-top:0; }}
    footer {{ text-align:center; padding:2rem; color:#94a3b8; font-size:0.85rem; border-top:1px solid #e2e8f0; }}
    @media (max-width: 640px) {{
      .wrap {{ grid-template-columns:1fr; }}
      nav {{ flex-wrap:wrap; gap:0.5rem; }}
      header {{ padding:1rem; }}
      header h1 {{ font-size:1.3rem; }}
    }}
    @media (min-width: 1024px) {{
      .wrap {{ max-width:1100px; }}
    }}
  </style>
</head>
<body>
<header><h1>{title}</h1><p>{desc}</p></header>
<nav>{nav_html}</nav>
<div class="wrap">
  <main>{body}</main>
  {aside}
</div>
<footer>BloggerEasy preview . Generated theme sidecar</footer>
</body>
</html>"""


def emit_preview_sidecar(xml_path: Path, structure: dict | None = None) -> Path | None:
    """Emit a responsive preview HTML file alongside the generated XML.

    If structure is provided, render a themed preview.
    Otherwise generate a generic XML-linked preview.
    """
    out_html = xml_path.with_suffix(".preview.html")

    if structure:
        html = structure_to_preview_html(structure)
    else:
        xml_name = xml_path.name
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>BloggerEasy . {escape(xml_name)} preview</title>
  <style>
    body {{ margin:0; font-family:system-ui,sans-serif; color:#222; background:#fafafa; }}
    header {{ background:#1a73e8; color:#fff; padding:1.5rem 2rem; }}
    header h1 {{ margin:0; }}
    .content {{ max-width:720px; margin:2rem auto; padding:0 1rem; }}
    .info {{ background:#fff; border:1px solid #e2e8f0; border-radius:8px; padding:1.5rem; }}
    .path {{ font-family:monospace; color:#64748b; font-size:0.9rem; }}
    footer {{ text-align:center; padding:2rem; color:#94a3b8; font-size:0.85rem; }}
    @media (max-width: 640px) {{
      header {{ padding:1rem; }}
      .content {{ margin:1rem auto; }}
    }}
  </style>
</head>
<body>
<header><h1>BloggerEasy Theme Preview</h1></header>
<div class="content">
  <div class="info">
    <p>Generated XML: <span class="path">{escape(xml_name)}</span></p>
    <p>This is a static sidecar preview. Open in any browser for a visual check before importing into Blogger.</p>
  </div>
</div>
<footer>BloggerEasy preview sidecar . Responsive HTML</footer>
</body>
</html>"""

    out_html.parent.mkdir(parents=True, exist_ok=True)
    out_html.write_text(html, encoding="utf-8")
    return out_html


def batch_preview_sidecars(xml_dir: Path) -> list[Path]:
    """Generate preview sidecars for all XML files in a directory."""
    results = []
    for xml_path in sorted(xml_dir.glob("*.xml")):
        sidecar = emit_preview_sidecar(xml_path)
        if sidecar:
            results.append(sidecar)
    return results
